source "https://rubygems.org"

gem "rails", "~> 8.1"

gem "bcrypt", "~> 3.1.7"
gem "bootsnap", require: false
gem "importmap-rails"
gem "jwt"
gem "propshaft"
gem "puma", ">= 5.0"
gem "sqlite3", ">= 2.1"
gem "stimulus-rails"
gem "turbo-rails"
gem "tzinfo-data", platforms: %i[windows jruby]

gem "pay", "~> 11.4"
gem "purchasekit-pay", "~> 0.1.4"

group :development do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "standard"
  gem "web-console"
end
